export const ADD_ARTICLE = 'ADD_ARTICLE';
export const FETCH_BREEDS_REQUEST = 'FETCH_BREEDS_REQUEST';
export const FETCH_BREEDS_SUCCESS = 'FETCH_BREEDS_SUCCESS';
export const FETCH_BREEDS_ERROR = 'FETCH_BREEDS_ERROR';
export const FILTER = 'FILTER';
